services:
  web:
    image: nginx:1.27
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${DATA_PATH}/nginx/logs:/var/log/nginx
      - ${SOURCE_PATH}/src:/var/www/src
    networks:
      - app_network

  app:
    build: ./php
    volumes:
      - ${SOURCE_PATH}/src:/var/www/src
    ports:
      - "${APP_VITE_PORT}:5173"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
